### ISSUE TITLE
LSZH TWR & Terminals missing

### ISSUE THREAD

**Issue by erikschroter** [mherweg/LSZH#1]
How do I properly install this into my FlightGear scenery for LSZH and I have tried a way I figured out and the model for everything but the terminals and the tower are there. I have the de-icing parts, the place with the smoke at one end of the runway with firefighters, hangar SR Technic but the Control Tower and the famous Zurich terminal aren't there... How can I fix it? How can I properly install this custom scenery into FlightGear (Mac/FG v3.4)
![screen shot 2015-09-22 at 9 19 29 pm](https://cloud.githubusercontent.com/assets/14793185/10028954/af1e22b2-616f-11e5-9b6b-dcce5eaf3823.png)
![screen shot 2015-09-22 at 9 19 37 pm](https://cloud.githubusercontent.com/assets/14793185/10028955/b2680be0-616f-11e5-8fa0-4fdf06a65be5.png)
![screen shot 2015-09-22 at 9 19 49 pm](https://cloud.githubusercontent.com/assets/14793185/10028957/b52cb880-616f-11e5-84e9-c52f392ff988.png)

**Comment by mherweg** [comment]
please have a look at the paths in the stg file.
some model files have to be put into Models/LSZH  folder , other models (those that work for you already) are in 
Objects/e000n40/e008n47.
Alternatively edit the paths in the  stg file and put all the Models(.ac .png and .xml) where you like.

move all .png files out of their folders (texturen, textures) so that they are  in the same folder as the .ac and .xml files.

**Comment by erikschroter** [comment]
Hey thanks for getting back to me so quickly, I have to check again but I put all the files into the scenery where LSZH is located then when to the exact location of LSZH in those files something like e0008n47. Then I removed the previous files for the airport and replaced them with the one that had the same name in your LSZH custom airport file. I separated the custom airport files into the objects and scenery in the scenery chunk file for the airport. I can't edit any .stg files so can you tell me where I should have them put as coded in the .stg file @mherweg ?
Erik Schröter

**Comment by erikschroter** [comment]
What do you mean that I have to do with Models/LSZH?

Erik Schröter

**Comment by erikschroter** [comment]
I can't edit any .stg files so can you tell me where I should have them put as coded in the .stg file?

Erik Schröter

**Comment by erikschroter** [comment]
@mherweg I have done everything you have said but yet I still have the same outcome no terminals nor the tower. Please help.

**Comment by erikschroter** [comment]
@mherweg nevermind I just found done it. :stuck_out_tongue_winking_eye:
